<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php
                    $_id=0;
                    foreach ($_product->getCategoryCollection() as $cat) {
                        $_array = $cat->getData();
                        $_id = $_array['entity_id'];
                    }

                    $objectManagerr = \Magento\Framework\App\ObjectManager::getInstance();
                    $categoryFactory = $objectManagerr->create('Magento\Catalog\Model\ResourceModel\Category\CollectionFactory');
                    $categoryy = $categoryFactory->create()
                        ->addAttributeToFilter('entity_id',$_id)
                        ->addAttributeToSelect('*');
                ?>
                <?php if($_product->getAttributeText('product_type') != 'banner') { ?>
                    <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                    <div class="product-item-info" data-container="product-grid">
                <?php } else {
                    echo($iterator++ == 1) ? '<li class="product-banner">' : '</li><li class="product-banner">';
                    ?>
                        <div class="product-item-banner">
                <?php } ?>
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <?php if($_product->getAttributeText('product_type') != 'banner') { ?>
                        <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                            <?php echo $productImage->toHtml(); ?>
                        </a>
                    <?php } else if($block->getMode() == 'grid') { ?>
                        <?php
                            //echo $productImage->toHtml();
                        ?>
                        <img src="<?php echo $block->getUrl('pub/media/catalog').'product'.$_product->getImage(); ?>"/>
                    <?php }?>

                    <div class="product details product-item-details">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <!-- check if banner image -->
                        <?php if($_product->getAttributeText('product_type') != 'banner') { ?>
                            <?php if ($block->getMode() == 'grid') { ?>
                                <strong class="product name product-item-name">
                                    <a class="product-item-link"
                                       href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                        <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                    </a>
                                    <br/>
                                    <label class="category-name">
                                        <?php
                                            foreach ($categoryy as $productt){
                                                echo $productt->getName();
                                            }
                                        ?>
                                    </label>
                                </strong>
                                <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                                <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                                <?php echo $block->getProductDetailsHtml($_product); ?>

                                <div class="product-item-inner">
                                    <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                        <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                            <?php if ($_product->isSaleable()): ?>
                                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                                    <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                                    <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                    <?php echo $block->getBlockHtml('formkey')?>
                                                    <button type="submit"
                                                            title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                            class="action tocart primary">
                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                    </button>
                                                </form>
                                            <?php else: ?>
                                                <?php if ($_product->getIsSalable()): ?>
                                                    <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                        <div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                                <a href="#"
                                                   class="action towishlist"
                                                   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                                                   data-action="add-to-wishlist"
                                                   role="button">
                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                                </a>
                                            <?php endif; ?>
                                        </div>
                                    </div>

                                </div>
                            <?php } else if ($block->getMode() == 'list') {?>
                                <table id="product-list-detail">
                                    <tbody>
                                        <tr>
                                            <td>
                                                <strong class="product name product-item-name">
                                                    <a class="product-item-link"
                                                       href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                                        <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                                    </a>&nbsp;&nbsp;
                                                    <label class="category-name">
                                                        <?php
                                                        foreach ($categoryy as $productt){
                                                            echo $productt->getName();
                                                        }
                                                        ?>
                                                    </label>
                                                </strong>
                                                <table id="product-list-attribute">
                                                    <tbody>
                                                    <tr>
                                                        <td><?php echo $block->escapeHtml(__('Manufacturer')); ?></td>
                                                        <td>
                                                            <?php
                                                            if(trim($_product->getAttributeText('manufacturer')) != '') {
                                                                echo $_product->getAttributeText('manufacturer');
                                                            } else {
                                                                echo 'OHNE';
                                                            }
                                                            ?>
                                                        </td>
                                                    </tr>
                                                    </tr>
                                                    <tr>
                                                        <td class="col label" scope="row">SKU</td>
                                                        <td class="col data" data-th="Breite"><?php echo $_product->getData('sku');?></td>
                                                    </tr>
                                                    <?php if(trim($_product->getData('baujahr')) != '') {?>
                                                        <tr>
                                                            <td class="col label" scope="row">Baujahr</td>
                                                            <td class="col data" data-th="Breite"><?php echo $_product->getData('baujahr');?></td>
                                                        </tr>
                                                    <?php } ?>
                                                    <tr>
                                                        <td class="col label" scope="row"><?php echo $block->escapeHtml(__('Delivery Time')); ?></td>
                                                        <td class="col data" data-th="Breite"><?php echo $_product->getData('delivery_time');?></td>
                                                    </tr>
                                                    </tbody>
                                                </table>
                                            </td>
                                            <td>
                                                <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                                                <span class="zzgl">
                                                    <label><?php echo $block->escapeHtml(__('taxinfo')); ?></label><br>
                                                    <a href="<?php echo $this->getUrl('lieferung');?>"><?php echo $block->escapeHtml(__('Shipping')); ?></a>
                                                </span>
                                                <div class="product-item-inner">
                                                    <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                                        <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                                            <?php if ($_product->isSaleable()): ?>
                                                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                                <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                                                    <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                                                    <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                                    <?php echo $block->getBlockHtml('formkey')?>
                                                                    <button type="submit"
                                                                            title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                                            class="action tocart primary">
                                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                                    </button>
                                                                </form>
                                                            <?php else: ?>
                                                                <?php if ($_product->getIsSalable()): ?>
                                                                    <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                                <?php else: ?>
                                                                    <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                                <?php endif; ?>
                                                            <?php endif; ?>
                                                        </div>
                                                        <div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                                                <a href="#"
                                                                   class="action towishlist"
                                                                   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                                   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                                   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                                                                   data-action="add-to-wishlist"
                                                                   role="button">
                                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                                                </a>
                                                            <?php endif; ?>
                                                        </div>
                                                    </div>
                                                </div><br/>
                                                <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
                                                   class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            <?php } ?>
                        <?php } ?>  <!-- end check if banner image -->
                    </div>
                </div>
                <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?php echo $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {    "[data-role=tocart-form], .form.map.checkout": {
			   "catalogAddToCart": {
				   "addToCartButtonTextDefault": "<?php echo __('Add to Cart'); ?>",
				   "addToCartButtonTextWhileAdding": "<?php echo __('Adding...'); ?>",
				   "addToCartButtonTextAdded": "<?php echo __('Added'); ?>"
			   }
		   }
		}
        </script>
    <?php endif; ?>
<?php endif; ?>

<script>
    require(
        [
            'jquery'
        ],
        function($) {
            setTimeout(function(){
                $('#layered-filter-block').css('display', 'block');
            }, 1000);
        }
    );
</script>