<?php
$order = $block->getOrder();
$store_email=$block->getStoreEmail();
$store_phone=$block->getStorePhone();
$store = $block->getStore();

?>
    <br><br>
    <tr>
        <td>
            <p>Rennhak Bäckerei-Technik GmbH<br>
                Feldstraße 1-2a<br>
                59192 Bergkamen<br>
                <br>
                Telefon: +49 (0) 23 89/27 57<br>
                Telefax: +49 (0) 23 89/92 89 440<br>
                Web: www.rennbatec.de<br>
                E-Mail: info@rennbatec.de<br>
                <br>
                Vertretungsberechtigter Geschäftsführer:<br>
                Paul-Wilhelm Rennhak<br>
                Registergericht: Amtsgericht Hamm<br>
                Registernummer: HRB 5125<br>
                Umsatzsteuer-Identifikationsnummer gemäß § 27a Umsatzsteuergesetz: DE228725288
                <br>
            </p>
        </td>
    </tr>

