<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/** @var \Magento\Catalog\Pricing\Render\FinalPriceBox $block */
/** @var \Magento\Catalog\Pricing\Price\ConfiguredPrice $configuredPrice */
$configuredPrice = $block->getPrice();
$schema = ($block->getZone() == 'item_view') ? true : false;
$priceLabel = ($block->getPriceLabel() !== null)
    ? $block->getPriceLabel()
    : '';
?>
<p class="price-as-configured">
    <strong><?php echo __('Price as configured:'); ?></strong>
    <?php /* @escapeNotVerified */ echo $block->renderAmount($configuredPrice->getAmount(), [
        'display_label'     => $priceLabel,
        'price_id'          => $block->getPriceId('product-price-'),
        'price_type'        => 'finalPrice',
        'include_container' => true,
        'schema' => $schema
    ]); ?>
</p>
<span class="zzgl">
    <label><?php echo $block->escapeHtml(__('taxinfo')); ?></label><br>
    <a href="<?php echo $this->getUrl('lieferung');?>"><?php echo $block->escapeHtml(__('Shipping')); ?></a>
</span>